### PR TITLE
fix(readme): Remove 3.2 from the readme and add 3.5

### PR DESCRIPTION
**Pull request by sjl2**
What: Update the README to reflect recent changes to the project setup
Why: Removed 3.2 support and the project also worked on 3.5

### CODE REVIEW

**Comment by charlesbjohnson** [comment]
LGTM

**Comment by dmlittle** [comment]
Currently we still support python 3.2 but we're not running our tests on it. If we want to stop supporting python 3.2, we should remove the restriction on the [`requests` version](https://github.com/lob/lob-python/blob/master/requirements.txt#L3).

**Comment by dmlittle** [comment]
I believe we also support `pypy` and `pypy3`.

**Comment by dmlittle** [comment]
Can  you add `"Programming Language :: Python :: 2.6"` to `setup.py`? Other than that LGTM.

**Pull request merged**
