### PR TITLE
parse_response now handles 504 Gateway Timeout errors

### LINKED ISSUE #103: Parsing a 504 error
Hey guys,
Sometimes we receive a HTTP 504 response error that is not appropriately being caught. In `parse_response` when you call [`payload = resp.json()`](https://github.com/lob/lob-python/blob/master/lob/api_requestor.py#L25), it will throw a `ValueError("No JSON object could be decoded")` error.

What I'm thinking of adding before `payload = resp.json()`:
```python
if resp.status_code == 504:
    raise error.APIConnectionError(resp.content,
        resp.content, resp.status_code, resp)
```

Thoughts? Happy to submit a PR if you think this is good.

### PR DESCRIPTION
**Pull request by FabioFleitas**
Closes #103

### CODE REVIEW

**Comment by robinjoseph08** [comment]
Looks like it's missing coverage, but that's to be expected. I don't think there's any easy way to mock out a 504 to ensure that it works, so can you just add `# pragma: no cover` to line 26?

```python
raise error.APIConnectionError(resp.content or resp.reason, # pragma: no cover
    resp.content, resp.status_code, resp)
```

**Comment by FabioFleitas** [comment]
@robinjoseph08 Done

**Comment by robinjoseph08** [comment]
Awesome, thanks a ton! I'll push a new version today :+1:

**Comment by robinjoseph08** [comment]
Version 2.24 has been released!

**Comment by FabioFleitas** [comment]
Awesome!

**Pull request merged**
