### PR TITLE
fix(coverage): increase coverage to 100%

### PR DESCRIPTION
**Pull request by elnaz**

### CODE REVIEW

**Comment by pon** [comment]
LGTM - I think you fixed this in your PR last week. @lob/api-engineering-team - if you run the coverage locally it is 100% but, we cannot get coveralls to match.

**Comment by leore** [comment]
can we add coverage enforcement?

**Comment by pon** [comment]
Its enforced on coveralls right now

**Comment by leore** [comment]
Where do you see that? Coveralls doesnt have an enforecemnt?

**Comment by pon** [comment]
Yeah at the bottom of the repo there is a coverage threshold you can set.

**Comment by elnaz** [comment]
I'm trying a couple of different things to see if I can get coverage to 100%. If that fails then I should lower the coverage threshold?

**Comment by pon** [comment]
Threshold is currently 99% on coveralls so if you can figure it out we can bump to 100%

**Comment by leore** [comment]
Where is the threshold set?

**Comment by pon** [comment]
Bottom of the page: https://coveralls.io/r/lob/lob-python

**Comment by elnaz** [comment]
I don't think this PR will fix it. Sorry I should have put WIP so you could ignore it. Once I've confirmed that this PR doesn't actually bring the coverage to 100% I'll close the PR and delete the branch.

**Comment by elnaz** [comment]
Huzzah! 
https://coveralls.io/builds/2365109

So the issue was that when exclude_lines has a value in the .coveragerc file, the standard pragma needs to be re-enabled. I re-enable pragma no cover in that config file and we're now up to 100%. Source: http://nedbatchelder.com/code/coverage/config.html

I'm going to remove the second pragma no cover line on that else statement and see if it will still work with just one pragma no cover. I'll ping you when this PR is ready for approval.

**Comment by leore** [comment]
woo hoo

**Comment by elnaz** [comment]
Okay, ready for review @leore and @pon

**Comment by leore** [comment]
LGTM . Great job figuring this out. I am all about 100% coverage and coverage enforcement.

**Comment by pon** [comment]
LGTM

**Pull request merged**
